all: 
	docbook2html book.xml
# To generate PDF, convert it to RTF first and then
# use MS Word or OpenOffice Writer program to convert 
# it into PDF. You need to insert figures manually.
rtf:
	docbook2rtf book.xml



