name: cmake

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for the develop branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab    
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Spack
      uses: actions/checkout@v2
      with:
        repository: HDFGroup/hdf5
        path: ./hdf5

    - name: Install dependencies
      run: sudo apt-get install ninja-build automake autoconf libtool libtool-bin

    - name: Run a multi-line script
      run: |
        mkdir ./hdf5/build
        cd ./hdf5/build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        sudo make install
        mkdir "${{ runner.workspace }}/build"
        cd "${{ runner.workspace }}/build"
        cmake ..
        ctest
