name: cmake

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for the develop branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab    
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout HDF5
      uses: actions/checkout@v2
      with:
        repository: HDFGroup/hdf5
        path: ./hdf5

    - name: Install dependencies
      run: sudo apt-get install ninja-build automake autoconf libtool libtool-bin
    - name: Install HDF5
      run: |
        mkdir ./hdf5/build
        cd ./hdf5/build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
        sudo make install
        cd ../..

    - name: Checkout HPF
      uses: actions/checkout@v2
      with:
        repository: hyoklee/hpf

    - name: Test performance
      run: |
        pwd
        ls .
        mkdir build
        cd build
        cmake ..
        make
        ./efc_no
        ctest
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ runner.workspace }}/hpf/build/Testing/*
