name: cmake
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: checkout h5
      uses: actions/checkout@v4
      with:
        repository: HDFGroup/hdf5
        path: hdf5

    - name: apt
      run: sudo apt-get install ninja-build automake autoconf libtool libtool-bin
    - name: install h5
      run: |
        mkdir hdf5/build
        cd hdf5/build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
        sudo make -j2 install
        cd ..
        git rev-parse HEAD > git.txt

    - name: perf
      run: |
        pwd
        ls
        mkdir build
        cd build
        cmake ..
        make
        ./efc_no | tee ../output.txt
        ./many_dsets | tee -a ../output.txt
        ./vds | tee -a ../output.txt
        ./cmpd_subset | tee -a ../output.txt
        cd ..
        pwd
        ls

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: git.txt
        path: ${{ runner.workspace }}/hpf/hdf5/git.txt

    - name: store
      uses: hyoklee/github-action-benchmark@v1
      with:
        name: Catch2 Benchmark
        tool: "catch2"
        output-file-path: ${{ runner.workspace }}/hpf/output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        skip-fetch-gh-pages: false
        auto-push: true
        alert-threshold: "100%"
        comment-on-alert: false
        fail-on-alert: false
        alert-comment-cc-users: "@hyoklee"
