name: dispatch
on: [repository_dispatch]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"    
    - name: Checkout HPF
      uses: actions/checkout@v2
    - name: Record time
      run: |
        date >> ChangeLog
    - name: Commit
      uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
