name: dispatch
on: [repository_dispatch]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"    
    - name: Checkout HPF
      uses: actions/checkout@v2
    - name: Commit to trigger a new action
      run: |
        date >> ChangeLog
        git add -u && git commit -m "Trigger by HDF5" && git push
